version: '3.1'

services:
   pgadmin:
     image: dpage/pgadmin4
     environment:
       PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
       PGADMIN_DEFAULT_PASSWORD: "admin"
     ports:
       - "5050:80"
     depends_on:
       - db
     networks:
       - my-network
   db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BaumanS2SBot
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network
   bot:
     build: .
     environment:
       TELEGRAM_API_TOKEN: ""
       DATASOURCE_NAME: ""
     depends_on:
       - db
     networks:
       - my-network
volumes:
  db:

networks:
  my-network:
    driver: bridge