version: '3.1'

services:
   db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BaumanS2SBot
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db:/var/lib/postgresql/data
   bot:
     build: .
     environment:
       TELEGRAM_API_TOKEN: ""
       DATASOURCE_NAME: ""
     depends_on:
       - db
volumes:
  db:
